In [38]:
# import libraries
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.tree  import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder

In [2]:
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('salaries.csv')
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [5]:
df.shape

(16, 4)

In [8]:
df.isnull().sum()

company                  0
job                      0
degree                   0
salary_more_then_100k    0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes


In [10]:
df.describe()

salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [12]:
LB = LabelEncoder()
df['company'] = LB.fit_transform(df['company'])
df['job'] = LB.fit_transform(df['job'])
df['degree'] = LB.fit_transform(df['degree'])

In [14]:
# company   2 -> google, 0 -> abcpharma, 1 ->facebook
# job       sales executive -> 2, business manager - 0, computer programmer - 1
# bachelor - 0 master - 1

In [15]:
df  

company  job  degree  salary_more_then_100k
0         2    2       0                      0
1         2    2       1                      0
2         2    0       0                      1
3         2    0       1                      1
4         2    1       0                      0
5         2    1       1                      1
6         0    2       1                      0
7         0    1       0                      0
8         0    0       0                      0
9         0    0       1                      1
10        1    2       0                      1
11        1    2       1                      1
12        1    0       0                      1
13        1    0       1                      1
14        1    1       0                      1
15        1    1       1                      1

In [16]:
df.describe()

company        job     degree  salary_more_then_100k
count  16.000000  16.000000  16.000000                 16.000
mean    1.125000   0.937500   0.500000                  0.625
std     0.806226   0.853913   0.516398                  0.500
min     0.000000   0.000000   0.000000                  0.000
25%     0.750000   0.000000   0.000000                  0.000
50%     1.000000   1.000000   0.500000                  1.000
75%     2.000000   2.000000   1.000000                  1.000
max     2.000000   2.000000   1.000000                  1.000

In [17]:
df.corr()

company       job        degree  \
company                1.000000e+00  0.108941 -1.777780e-17   
job                    1.089410e-01  1.000000  7.559289e-02   
degree                -1.777780e-17  0.075593  1.000000e+00   
salary_more_then_100k  1.240347e-01 -0.370842  2.581989e-01   

                       salary_more_then_100k  
company                             0.124035  
job                                -0.370842  
degree                              0.258199  
salary_more_then_100k               1.000000

In [18]:
X = df.drop(columns =['salary_more_then_100k'])
Y = df['salary_more_then_100k']

In [19]:
X

company  job  degree
0         2    2       0
1         2    2       1
2         2    0       0
3         2    0       1
4         2    1       0
5         2    1       1
6         0    2       1
7         0    1       0
8         0    0       0
9         0    0       1
10        1    2       0
11        1    2       1
12        1    0       0
13        1    0       1
14        1    1       0
15        1    1       1

In [20]:
Y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [21]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1)

In [23]:
X_train.shape

(14, 3)

In [31]:
Y_test.shape

(2,)

In [25]:
model_log = LogisticRegression()
model_tree = DecisionTreeClassifier()

In [26]:
model_log.fit(X_train,Y_train)

LogisticRegression()

In [27]:
model_tree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [29]:
model_log.predict(X_test)

array([0, 1], dtype=int64)

In [32]:
model_tree.predict(X_test)

array([1, 1], dtype=int64)

In [33]:
model_log.score(X_train,Y_train)

0.7142857142857143

In [34]:
model_tree.score(X_train,Y_train)

1.0

In [35]:
model_tree_reg = DecisionTreeRegressor()
model_tree_reg.fit(X_train,Y_train)

DecisionTreeRegressor()

In [36]:
model_tree_reg.predict(X_test)

array([1., 1.])

In [37]:
model_tree_reg.score(X_train,Y_train)

1.0